### ISSUE TITLE
Empty Sam File after ralign

### ISSUE THREAD

**Issue by mattdmem** [TimD1/nPoRe#2]
```
python ~/wc/npore/src/realign.py --bam <BAM> --ref <FASTA> --out_prefix <PREFIX>  --stats_dir ~/wc/npore/guppy5_stats
```
Results in an empty sam file with the only error a warning:

```
lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 12 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```
`samtools flagstat` on my bam:
```
8898 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
8898 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
Contig header line matches contig in the bam file. This is amplicon data - so only small regions of the entire genome is covered.

Any ideas?

**Comment by mattdmem** [comment]
Looks like it works using your docker container!

**Comment by TimD1** [comment]
Glad the Docker container worked for you!

I'm surprised you're running into so many issues outside the container, though; not sure what could be causing this.

Please let me know if you do run into any further issues, especially within the container

**Comment by cfblaeb** [comment]
Also getting an empty sam file (contains header, but no reads).
However the result is the same with/without docker (via docker hub).

**Comment by TimD1** [comment]
What exact command line parameters are you using? Could you provide a sample BAM, and other system information that may be relevant? I haven't been able to reproduce this issue yet, but would like to fix it if multiple people have run into it.

**Comment by cfblaeb** [comment]
I'm on ubuntu 22.04
I install python3-venv and python3-pip
Then run the command from your readme: "git clone https://github.com/TimD1/npore && cd npore && make"
Then, again per the readme, I run:
. ./venv3/bin/activate
python3 ./src/realign.py --help

The first command correctly activates the environment.
The second fails because numpy is not installed. I am not sure why it doesnt get installed in the environment. I suspect its something todo with your makefile.

Anyway I then run
pip install -r requirements.txt
which installs 
"Successfully installed biopython-1.79 cycler-0.11.0 cython-0.29.30 fonttools-4.33.3 kiwisolver-1.4.2 matplotlib-3.5.2 numpy-1.22.4 packaging-21.3 pillow-9.1.1 psutil-5.9.1 pyparsing-3.0.9 pysam-0.19.1 python-dateutil-2.8.2 six-1.16.0"

and now "python3 ./src/realign.py --help" executes correctly.

I then cd to my work folder where the bam and fasta file are in the output folder (attached zip file)
I then run
python npore/src/realign.py --bam output/map.bam --ref output/UMI_fasta_preadator.fasta --out_prefix output/rea --stats_dir output/gp5_stats

This outputs
> selecting BAM regions
> reading reference
> calculating confusion matrices
    1 of 1 chunks processed. 
> calculating score matrices
> creating output SAM
> extracting read data from BAM
> computing individual read realignments

    runtime: 0.02s

and it results in an empty sam file (header only)

[output.zip](https://github.com/TimD1/nPoRe/files/8822501/output.zip)

**Comment by TimD1** [comment]
Thanks for providing such detailed information! 

I've fixed the issue, which was caused by both an empty Q-score string and a non-existent MD tag in the initial BAM file. This was causing the read info generator to fail silently, and not process any reads. It should work on your files now, provided you used `samtools calmd` to annotate it. I've made this prerequisite clear [in the README now](https://github.com/TimD1/nPoRe#prerequisites).

I've also changed the README build process, since the Makefile workflow seems to be broken. Sorry this fix is coming so late!
